---
# handlers file for docker

- name: Restart Docker
  service:
      name: docker
      state: restarted

- name: Restart UFW
  service:
      name: ufw
      state: restarted

- name: Reset connection
  meta: reset_connection
